title: "Xian Zhang"
email: zhangxian@shao.ac.cn
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "/XianZhang123.github.io" 
twitter_username: None
github_username:  XianZhang123

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
